language: r
sudo: false
dist: trusty

os:
  - linux
  - osx
  
latex: true

warnings_are_errors: false

cache: packages
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'pkgdown::build_site()'
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
